
game:
  real_world_seconds_per_day: 6 * 60
  version: 0.2.6-staging
gcloud:
  project: the-promised-land-dev
  zone: us-east4-c
  
main:
- dir: server/infra/gcp
  name: infra
  steps:
  - cmd: gg build-templates .
    desc: building templates for infra
  - cmd: terraform init
    desc: setting up terraform
  - cmd: ./tf_import.sh
    desc: importing existing resources via terraform
  - cmd: terraform apply -auto-approve
    desc: updating infrastructure if needed
  - cmd: gg update-profile nakama.host $(terraform output -raw server_ip)
    desc: setting IP of host to current profile
- dir: game
  name: game-client
  steps:
  - cmd: gg build-templates .
    desc: building templates for game client
  - cmd: BUILD_ENV=staging ./build_clients.sh
    desc: building game clients for distros
  - cmd: butler push ./dist/mac newnoiseworks/the-promised-land-dev:mac
    desc: itch.io butler push on mac build
  - cmd: butler push ./dist/windows newnoiseworks/the-promised-land-dev:windows
    desc: itch.io butler push on windows build
  - cmd: butler push ./dist/x11 newnoiseworks/the-promised-land-dev:linux
    desc: itch.io butler push on x11 build
- dir: server
  name: nakama-server
  steps:
  - cmd: gg build-templates .
    desc: building templates for game server
  - cmd: cp -rf ../game/dist/web-staging/* nakama/website
    desc: copy web build into server
  - cmd: GCP_PROJECT=the-promised-land-dev GCP_ZONE=us-east4-c ./deploy.sh
    desc: deploy game server to GCP
    dir: deploy/gcp


nakama:
  host: ???
  port: 7350
  secure: false
  key: default-key


tasks:
- name: update-templates
  steps:
  - cmd: gg build-templates .
  dir:
- dir: server/infra/gcp
  name: destroy-infra
  steps:
  - cmd: gg build-templates .
  - cmd: terraform init
  - cmd: ./tf_import.sh
  - cmd: terraform destroy -auto-approve
