omgd:
  deploy:
    server:
      gcloud:
        project: the-promised-land-production
        zone: us-east1-d
        machine_type: e2-small
    game:
      itchio:
        project: the-promised-land
        user: newnoiseworks

####
game:
  real_world_seconds_per_day: 12 * 60
  version: 0.2.6

