omgd:
  deploy:
    server:
      gcloud:
        project: the-promised-land-dev
        zone: us-east4-c
    game:
      itchio:
        project: the-promised-land-dev
        user: newnoiseworks

####
game:
  real_world_seconds_per_day: 6 * 60
  version: 0.2.6-staging
